apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-city-weahter-app
  namespace: argocd 
spec:
  destination: 
    namespace: gitops-kubernetes
    server: https://kubernetes.default.svc 
  project: default 
  source:
    repoURL: https://github.com/agallo73/ArgoCD-AutoPilot.git
    path: deployment
    targetRevision: main
