apiVersion: apps/v1
kind: Deployment
metadata:
  name: ermes-app
  labels:
    app: ermes-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: ermes-app
  template:
    metadata:
      labels:
        app: ermes-app
    spec:
      containers:
      - name: ermes-app
        image: antkr73/gitlab-actions:1.0
        ports:
        - containerPort: 8080
        # resources:
        #   requests:
        #     memory: "64Mi"
        #     cpu: "250m"
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
